### ISSUE TITLE
Realmspace: New book

### ISSUE THREAD

**Issue by TBigLyfe** [decheine/complete-compendium#222]
Book title: SJR2 - Realmspace
Book year: 1991
Book author: Dale "Slade" Henson, Karen S. Boomgarden, Gary L. Thomas
Book publish_id: 9312
ISBN10 1-5607-6052-4

New monsters:
- [x] Anadjiin
- [x] Dragon, Air
- [x] Fish, Chandos
- [x] Halfling, Anadian
- [x] Helian
- [x] Lavaworm
- [x] Oortling
- [x] Plainsjan
- [x] Praying Mantis, Gargantuan

**Comment by decheine** [comment]
Thank you! If you don't mind I'm going to make some edits to the issue for some details. I have the pdf and these are indeed all new monsters. I'll prioritize this one since it's more "core" than the dragon magazines and such.

**Comment by TBigLyfe** [comment]
> Thank you! If you don't mind I'm going to make some edits to the issue for some details. I have the pdf and these are indeed all new monsters. I'll prioritize this one since it's more "core" than the dragon magazines and such.

I am the Anadjiin's greatest fan so I was lowkey sad to see they were not in the Appendix, hope to see them soon! Love this project and I hope it stays online forever! Amazing job and thank you, it is really useful for all my games.

**Comment by decheine** [comment]
Hey Anadjiin's greatest fan, do you know if it's supposed to have magic resistance? It's statblock skips magic resistance completely, and it could be a printing error and  it's definitely not a PDF error since it was image based. It's MR is probably Nil but I thought I'd ask to be sure!

**Comment by decheine** [comment]
Pushed 3e36564 and they all look good now. Thanks again for pointing out this book!

**Comment by TBigLyfe** [comment]
> Hey Anadjiin's greatest fan, do you know if it's supposed to have magic resistance? It's statblock skips magic resistance completely, and it could be a printing error and it's definitely not a PDF error since it was image based. It's MR is probably Nil but I thought I'd ask to be sure!

Sorry man I wouldn't know more than you about this but I do think it's probably Nil. thank you! I'm glad to have contributed to this even if just a fracture, this is awesome.

**Comment by decheine** [comment]
> > Hey Anadjiin's greatest fan, do you know if it's supposed to have magic resistance? It's statblock skips magic resistance completely, and it could be a printing error and it's definitely not a PDF error since it was image based. It's MR is probably Nil but I thought I'd ask to be sure!
> 
> Sorry man I wouldn't know more than you about this but I do think it's probably Nil. thank you! I'm glad to have contributed to this even if just a fracture, this is awesome.

No worries, this book especially has a lot of mistakes 😅 

Anadjiin is live at completecompendium.com/appendix/anadjiin and its book page  completecompendium.com/catalog/sj/9312/anadjiin/
