### ISSUE TITLE
2102:  MC1 Volume I (w/binder # 1)

### ISSUE THREAD

**Issue by decheine** [decheine/complete-compendium#57]
existing

- [x] mammherd
- [x] beholde1
- [x] cavefish
- [x] centaur
- [x] centiped
- [x] chimera
- [x] cockatri
- [x] couatl
- [x] dispbeas
- [x] dog
- [x] dragon (needs more work)
- [x] dragcbla
- [x] dragcblu
- [x] dragcred
- [x] dragcgre
- [x] dragcwhi
- [x] drgturtl
- [x] drgnfish
- [x] elementa
- [x] element1
- [x] element2
- [x] elf
- [x] genie
- [x] ghost
- [x] ghoul
- [x] gianclou
- [x] gianfire
- [x] gianfros
- [x] gianhill
- [x] gianston
- [x] gianstor
- [x] gnome
- [x] goblin
- [x] golem1
- [x] golem2
- [x] halfling
- [x] harpy
- [x] hydra
- [x] imp
- [x] invistal
- [x] kobold
- [x] lycawera
- [x] skunk
- [x] snake

**Comment by decheine** [comment]
existing

- [ ] mammherd
- [ ] beholde1
- [ ] cavefish
- [ ] centaur
- [ ] centiped
- [ ] chimera
- [ ] cockatri
- [ ] couatl
- [ ] dispbeas
- [ ] dog
- [ ] dragon (needs more work)
- [ ] dragcbla
- [ ] dragcblu
- [ ] dragcred
- [ ] dragcgre
- [ ] dragcwhi
- [ ] drgturtl
- [ ] drgnfish
- [ ] elementa
- [ ] element1
- [ ] element2
- [ ] elf
- [ ] genie
- [ ] ghost
- [ ] ghoul
- [ ] gianclou
- [ ] gianfire
- [ ] gianfros
- [ ] gianhill
- [ ] gianston
- [ ] gianstor
- [ ] gnome
- [ ] goblin
- [ ] golem1
- [ ] golem2
- [ ] halfling
- [ ] harpy
- [ ] hydra
- [ ] imp
- [ ] invistal
- [ ] kobold
- [ ] lycawera
- [ ] skunk
- [ ] snake

**Comment by m0rgi0n999** [comment]
might i ask why this one is closed while the Brass, Bronze, Copper, Gold and Silver dragons from the 2102 MC 1 are not in here?
